services:
  wordpress:
    image: wordpress:php8.2-fpm-alpine
    platform: linux/arm64/v8
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    platform: linux/arm64/v8
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: somewordpress
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    platform: linux/arm64/v8
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WORDPRESS_API_URL=http://wordpress:80
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - wordpress

volumes:
  wordpress_data:
  db_data: 